// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC9NEm5rYcjS9bL9hsaEHmXeNB5w88d8ts',
    appId: '1:437935610778:web:1f638ca8128c309964b823',
    messagingSenderId: '437935610778',
    projectId: 'saive-eaa4e',
    authDomain: 'saive-eaa4e.firebaseapp.com',
    storageBucket: 'saive-eaa4e.appspot.com',
    measurementId: 'G-TW7W0WPQH8',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB58vL7eDE3m_I-pLxKAdYJcVnZJ5tsQcg',
    appId: '1:437935610778:android:73c5355e421d7bc864b823',
    messagingSenderId: '437935610778',
    projectId: 'saive-eaa4e',
    storageBucket: 'saive-eaa4e.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCYHT3LuXckY9VuRT-TtLnuiZjWl4F1ojY',
    appId: '1:437935610778:ios:3117c3c75a4bdf4164b823',
    messagingSenderId: '437935610778',
    projectId: 'saive-eaa4e',
    storageBucket: 'saive-eaa4e.appspot.com',
    iosBundleId: 'com.example.saive',
  );
}
